### PR TITLE
app-misc/anki-bin: Add binary version of Anki

### PR DESCRIPTION
**Pull request by goduck777**
Add an ebuild for the binary version of Anki app: https://apps.ankiweb.net/

### CODE REVIEW

**Comment by BlueManCZ** [comment]
Thank you for your contribution! :octocat:

**Comment by BlueManCZ** [comment]
Could you please test it after my [latest edit](https://github.com/BlueManCZ/edgets/commit/993e25897fff69c3e2f9e0d2cef4dd59245eccec)? I don't have systemd, so I can't do it myself.

**Comment by goduck777** [comment]
@BlueManCZ It works well. Thanks for the update.

I was not aware that it depends on systemd. What error did you get?

**Comment by BlueManCZ** [comment]
Thanks for the test. I got this error at runtime:

```
Traceback (most recent call last):
  File "runanki.py", line 3, in <module>
  File "/home/dae/venv/lib/python3.8/site-packages/PyInstaller-4.0.dev0+g2886519-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 625, in exec_module
  File "aqt/__init__.py", line 20, in <module>
  File "/home/dae/venv/lib/python3.8/site-packages/PyInstaller-4.0.dev0+g2886519-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 625, in exec_module
  File "aqt/qt.py", line 18, in <module>
ImportError: libsystemd.so.0: cannot open shared object file: No such file or directory
[17176] Failed to execute script runanki
```

**Comment by goduck777** [comment]
Can you please try this patch on your system?

https://gist.github.com/goduck777/c1d7ecb333fa9b0d6dc6b40b16318d9a

**Comment by BlueManCZ** [comment]
It indeed works fine with your [suggested update](https://github.com/BlueManCZ/edgets/commit/3f74f52055827759b747a4754f5e6a3f2bd14f2f).

**Comment by goduck777** [comment]
Glad to know that 😄

**Pull request merged**
