### PR TITLE
x11-libs/bamf: fix ebuilds

### PR DESCRIPTION
**Pull request by nick87720z**
First - even configuration failed. Now should work, but I found that test-bamf fails on `make check` (test-libbamf passes).
Can't understand effect from --disable-gtktest.

- vapigen is set via VALA_API_GEN
- VALA_USE_DEPEND - better be before inherit
- moved build deps to BDEPEND
- added USE=dbusmenu
- don't ignore test feature (test-bamf fails for 0.5.5)

### CODE REVIEW

**Comment by BlueManCZ** [comment]
Hello. That's strange. Both ebuilds 0.5.5 and 9999 emerge just fine for me as they are. But thank you for your contribution, I will look into it. Can you provide your error messages, please?

**Comment by nick87720z** [comment]
Without modifications - it's just configure, which can't find `vapigen`, because eclass sets it in VAPIGEN var, but configure expects VALA_API_GEN. This is all error I had.

Could be that you have `vapigen` unversioned executable, which is probably symlink? This could make it to work, but you could eventually find, that used unversioned vapigen has different version that e.g. valac, picked by configuration from VALAC variable.

Did not try live ebuild yet, only release.

**Comment by BlueManCZ** [comment]
Yes, you are right. I have `vapigen` symlinked to `/usr/bin/vapigen-0.48`. I tested live ebuild now and it works just fine. Thank you!

**Comment by nick87720z** [comment]
Perhaps would be better to rename dbusmenu use flag to dbus. The dbusmenu flat is only used by xfce4-panel from all packages, while plank uses dbus flag for same dependency (even your plank ebuild).
I found it just now, while checking your plank ebuild, comparing with one from elementary repo, which I used before.
Also I did not know (or forgot) xdg.eclass, using instead xdg-utils.eclass.

**Comment by BlueManCZ** [comment]
> Also I did not know (or forgot) xdg.eclass, using instead xdg-utils.eclass.

What do you mean?

**Comment by nick87720z** [comment]
> What do you mean?

Nevermind. I left it instead of some pointless recomentation about these eclasses.

**Pull request merged**
